name: CI
on: [push, pull_request]
jobs:
    linux-ci:
        name: Linux
        strategy:
            fail-fast: false
            matrix:
                build_type: [Release, Debug]
                config:
                    - cc: gcc-9
                      cxx: g++-9
                      os: ubuntu-20.04

                    - cc: gcc-10
                      cxx: g++-10
                      os: ubuntu-20.04

                    - cc: gcc-11
                      cxx: g++-11
                      os: ubuntu-22.04

                    - cc: gcc-12
                      cxx: g++-12
                      os: ubuntu-22.04

                    - cc: clang-10
                      cxx: clang++-10
                      os: ubuntu-20.04

                    - cc: clang-11
                      cxx: clang++-11
                      os: ubuntu-20.04

                    - cc: clang-12
                      cxx: clang++-12
                      os: ubuntu-20.04

                    - cc: clang-13
                      cxx: clang++-13
                      os: ubuntu-22.04

                    - cc: clang-14
                      cxx: clang++-14
                      os: ubuntu-22.04
        runs-on: ${{matrix.config.os}}
        env:
            CC: ${{matrix.config.cc}}
            CXX: ${{matrix.config.cxx}}
            PYTHON_EXECUTABLE: /usr/bin/python
            PYTHON3_EXECUTABLE: /usr/bin/python3
            INSTALL_PREFIX: /usr/local
        steps:
          - uses: actions/checkout@v2
          - name: Install dependencies
            run: |
                sudo apt update --fix-missing
                sudo apt install -y libpython2-dev libpython3-dev python3-numpy doxygen

                # Note: we need the grep because apt-cache will return 0 even when no packages are found
                if sudo apt-cache search python-numpy | grep 'numpy -'; then sudo apt install -y python-numpy; fi
                if sudo apt-cache search python2-numpy | grep 'numpy -'; then sudo apt install -y python2-numpy; fi
          - name: Build SoapySDR
            run: |
                mkdir -p ${{github.workspace}}/build
                cd ${{github.workspace}}/build
                cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE} -DPYTHON3_EXECUTABLE=${PYTHON3_EXECUTABLE} ${{github.workspace}}
                make
          - name: Install
            run: |
                cd ${{github.workspace}}/build
                sudo make install
                sudo ldconfig
          - name: Run unit tests
            run: |
                cd ${{github.workspace}}/build
                ctest --output-on-failure
          - name: Test SoapySDRUtil
            run: |
                SoapySDRUtil --info
                SoapySDRUtil --check=null
                SoapySDRUtil --make="driver=null"
          - name: Test Python bindings
            run: |
                export PYTHONPATH=$(${PYTHON_EXECUTABLE} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(plat_specific=True, prefix='${INSTALL_PREFIX}'))")
                echo ${PYTHONPATH}
                ${PYTHON_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.getAPIVersion())"
                ${PYTHON_EXECUTABLE} -c "from SoapySDR import *; print(SOAPY_SDR_ABI_VERSION)"
                ${PYTHON_EXECUTABLE} -c "from SoapySDR import *; print(SOAPY_SDR_TIMEOUT)"
                ${PYTHON_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.errToStr(SoapySDR.SOAPY_SDR_TIMEOUT))"
                ${PYTHON_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.Device.make('driver=null'))"
          - name: Test Python3 bindings
            run: |
                export PYTHONPATH=$(${PYTHON3_EXECUTABLE} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(plat_specific=True, prefix='${INSTALL_PREFIX}'))")
                echo ${PYTHONPATH}
                ${PYTHON3_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.getAPIVersion())"
                ${PYTHON3_EXECUTABLE} -c "from SoapySDR import *; print(SOAPY_SDR_ABI_VERSION)"
                ${PYTHON3_EXECUTABLE} -c "from SoapySDR import *; print(SOAPY_SDR_TIMEOUT)"
                ${PYTHON3_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.errToStr(SoapySDR.SOAPY_SDR_TIMEOUT))"
                ${PYTHON3_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.Device.make('driver=null'))"
          - name: Test module registration
            run: |
                mkdir -p ${{github.workspace}}/build-example
                cd ${{github.workspace}}/build-example
                cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{github.workspace}}/ExampleDriver
                sudo make install
                SoapySDRUtil --check=my_device
    osx-ci:
        name: OS X
        strategy:
            fail-fast: false
            matrix:
                build_type: [Release, Debug]
                config:
                    - cc: gcc-9
                      cxx: g++-9
                      os: macos-11

                    - cc: gcc-10
                      cxx: g++-10
                      os: macos-11

                    - cc: gcc-11
                      cxx: g++-11
                      os: macos-11

                    - cc: clang
                      cxx: clang++
                      os: macos-11

                    # TODO: re-enable after MacOS Monterey Python issue fixed
                    #
                    #- cc: clang
                    #cxx: clang++
                    #os: macos-12
        runs-on: ${{matrix.config.os}}
        env:
            CC: ${{matrix.config.cc}}
            CXX: ${{matrix.config.cxx}}
            PYTHON_EXECUTABLE: /usr/bin/python
            PYTHON3_EXECUTABLE: /usr/bin/python3
            INSTALL_PREFIX: /usr/local
        steps:
          - uses: actions/checkout@v2
          - name: Install dependencies
            run: |
                pip install numpy
                pip3 install numpy
          - name: Build SoapySDR
            run: |
                mkdir -p ${{github.workspace}}/build
                cd ${{github.workspace}}/build
                cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE} -DPYTHON3_EXECUTABLE=${PYTHON3_EXECUTABLE} ${{github.workspace}}
                make
          - name: Install
            run: |
                cd ${{github.workspace}}/build
                sudo make install
          - name: Run unit tests
            run: |
                cd ${{github.workspace}}/build
                ctest --output-on-failure
          - name: Test SoapySDRUtil
            run: |
                SoapySDRUtil --info
                SoapySDRUtil --check=null
                SoapySDRUtil --make="driver=null"
          - name: Test module registration
            run: |
                mkdir -p ${{github.workspace}}/build-example
                cd ${{github.workspace}}/build-example
                cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{github.workspace}}/ExampleDriver
                sudo make install
                SoapySDRUtil --check=my_device
    windows-ci:
        name: Windows
        strategy:
            fail-fast: false
            matrix:
                build_type: [Release, Debug]
                config:
                    #
                    # MSVC
                    #

                    - cmake_config: -G "Visual Studio 14 2015" -A "Win32"
                      arch: win32
                      os: windows-2019
                      msvc: true

                    - cmake_config: -G "Visual Studio 14 2015" -A "x64"
                      arch: x64
                      os: windows-2019
                      msvc: true

                      # Note: skipping VS2017, possible bugginess in parallel installs

                    - cmake_config: -G "Visual Studio 16 2019" -A "Win32"
                      arch: win32
                      os: windows-2019
                      msvc: true

                    - cmake_config: -G "Visual Studio 16 2019" -A "x64"
                      arch: x64
                      os: windows-2019
                      msvc: true

                    - cmake_config: -G "Visual Studio 17 2022" -A "Win32"
                      arch: win32
                      os: windows-2022
                      msvc: true

                    - cmake_config: -G "Visual Studio 17 2022" -A "x64"
                      arch: x64
                      os: windows-2022
                      msvc: true

                    #
                    # MinGW
                    #

                    - cmake_config: -G "MinGW Makefiles"
                      os: windows-2019
                      msvc: false

                    # TODO: reenable if Github updates GCC past 11.2
                    #- cmake_config: -G "MinGW Makefiles"
                    #  os: windows-2022
                    #  msvc: false
        runs-on: ${{matrix.config.os}}
        env:
            # Easier to have multiple copies of a subpath than deal with CI path parsing issues
            INSTALL_PREFIX: 'C:\Program Files\SoapySDR'
        steps:
          - uses: actions/checkout@v2
          - uses: ilammy/msvc-dev-cmd@v1
            if:
                ${{matrix.config.msvc == true}}
            with:
                arch: ${{matrix.config.arch}}
          - name: Build SoapySDR
            run: |
                mkdir ${{github.workspace}}\build
                cd ${{github.workspace}}\build
                cmake ${{matrix.config.cmake_config}} -DENABLE_PYTHON=OFF -DCMAKE_INSTALL_PREFIX="$Env:INSTALL_PREFIX" -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{github.workspace}}
                cmake --build . --config ${{matrix.build_type}}
          - name: Install
            run: |
                cd ${{github.workspace}}\build
                cmake --install . --config ${{matrix.build_type}}
          - name: Run unit tests
            run: |
                $Env:PATH += ";$Env:INSTALL_PREFIX\bin"
                cd ${{github.workspace}}\build
                ctest --output-on-failure -C ${{matrix.build_type}}
          - name: Test SoapySDRUtil
            run: |
                $Env:PATH += ";$Env:INSTALL_PREFIX\bin"
                SoapySDRUtil --info
                SoapySDRUtil --check=null
                SoapySDRUtil --make="driver=null"
          - name: Test module registration
            run: |
                $Env:PATH += ";$Env:INSTALL_PREFIX\bin"
                mkdir -p ${{github.workspace}}\build-example
                cd ${{github.workspace}}\build-example
                cmake ${{matrix.config.cmake_config}} -DCMAKE_INSTALL_PREFIX="$Env:INSTALL_PREFIX" -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{github.workspace}}\ExampleDriver
                cmake --build . --config ${{matrix.build_type}}
                cmake --install . --config ${{matrix.build_type}}
                SoapySDRUtil --check=my_device
    freebsd-ci:
        name: FreeBSD
        runs-on: macos-12
        env:
            INSTALL_PREFIX: /usr/local
            PYTHON_EXECUTABLE: /usr/local/bin/python3.9
        strategy:
            fail-fast: false
            matrix:
                build_type: [Release, Debug]
                release: ["12.3", "13.1"] # TODO: re-enable 13.0 after Python issue fixed
        steps:
        - uses: actions/checkout@v2
        - uses: vmactions/freebsd-vm@v0
          name: Test in FreeBSD
          with:
              envs: "INSTALL_PREFIX PYTHON_EXECUTABLE"
              release: ${{matrix.release}}
              copyback: false
              prepare: |
                  pkg install -y cmake devel/swig lang/python3
              run: |
                  # We can't separate these steps, so add prints for clarity.

                  echo
                  echo "----------------------------------"
                  echo "Building..."
                  echo "----------------------------------"
                  mkdir build
                  cd build
                  cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{github.workspace}}
                  make

                  echo
                  echo "----------------------------------"
                  echo "Installing..."
                  echo "----------------------------------"
                  make install

                  echo
                  echo "----------------------------------"
                  echo "Running unit tests..."
                  echo "----------------------------------"
                  ctest --output-on-failure

                  echo
                  echo "----------------------------------"
                  echo "Testing SoapySDRUtil..."
                  echo "----------------------------------"
                  SoapySDRUtil --info
                  SoapySDRUtil --check=null
                  SoapySDRUtil --make="driver=null"

                  echo
                  echo "----------------------------------"
                  echo "Testing Python bindings..."
                  echo "----------------------------------"
                  ${PYTHON_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.getAPIVersion())" || exit 1
                  ${PYTHON_EXECUTABLE} -c "from SoapySDR import *; print(SOAPY_SDR_ABI_VERSION)" || exit 1
                  ${PYTHON_EXECUTABLE} -c "from SoapySDR import *; print(SOAPY_SDR_TIMEOUT)" || exit 1
                  ${PYTHON_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.errToStr(SoapySDR.SOAPY_SDR_TIMEOUT))" || exit 1
                  ${PYTHON_EXECUTABLE} -c "import SoapySDR; print(SoapySDR.Device.make('driver=null'))" || exit 1

                  echo
                  echo "----------------------------------"
                  echo "Testing module registration..."
                  echo "----------------------------------"
                  mkdir -p ${{github.workspace}}/build-example
                  cd ${{github.workspace}}/build-example
                  cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{github.workspace}}/ExampleDriver
                  make install
                  SoapySDRUtil --check=my_device
